language: r
sudo: required
notifications:
    email: false
apt_packages:
    - libhdf5-7
    - libhdf5-dev
    - libhdf5-serial-dev
    - libgdal1h
    - libnetcdf-dev
    - libhdf4-alt-dev
    - libgdal-dev
    - libproj-dev
